#This is the playbook for
#installing Prometheus to the remote servers

---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install wget (CentOS)
    yum:
      name: wget
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu_prometheus
  become: true
  roles:
    - ubuntu_prometheus

- hosts: centos_prometheus
  become: true
  roles:
    - centos_prometheus
